### ISSUE TITLE
Unnecesary charges

### ISSUE THREAD

**Issue by bisskar** [Azure/terraform-azurerm-avm-ptn-alz-management#71]
Sugestion regarding "Complete" example, deploying LAW with reservation capacity cost $474.72/day as soon as you ingest any log. For an example for less aware people or someone who just want to learn it leads to unnecessary charges, I think good idea would be to comment/comment it out or change to PerGB2018. 

log_analytics_workspace_sku                                = "CapacityReservation"
log_analytics_workspace_reservation_capacity_in_gb_per_day = 200
to:
log_analytics_workspace_daily_quota_gb                     = null
log_analytics_workspace_sku                                = "PerGB2018"

**Comment by luke-taylor** [comment]
Hey, the defaults reflect those documented on the `azurerm_log_analytics_resource` https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_workspace

Would an additional example called "dev" be helpful, which would contain a lower costing configuration?

**Comment by matt-FFFFFF** [comment]
FYI @luke-taylor I added a warning to the README in #74

**Comment by matt-FFFFFF** [comment]
Warning has been added to the example #RR

**Comment by bisskar** [comment]
thanks, I guess it issue can be closed now
